In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
np.random.seed(42)

data = pd.DataFrame({
    "Area_sqft": np.random.randint(800, 3000, 100),
    "Bedrooms": np.random.randint(1, 5, 100),
    "Age_years": np.random.randint(1, 30, 100),
    "Distance_km": np.random.uniform(1, 20, 100)
})

data["Price_lakhs"] = (
    0.08 * data["Area_sqft"]
    + 8 * data["Bedrooms"]
    - 0.7 * data["Age_years"]
    - 1.2 * data["Distance_km"]
    + np.random.normal(0, 10, 100)
)

data.head()

   Area_sqft  Bedrooms  Age_years  Distance_km  Price_lakhs
0       1660         2         28    12.522152    93.921992
1       2094         2         22     1.174744   168.574850
2       1930         4         23     2.927959   160.168584
3       1895         1          5    13.606534   148.296493
4       2438         3          1     1.096170   209.099389

In [6]:
X = data[["Area_sqft", "Bedrooms", "Age_years", "Distance_km"]]
y = data["Price_lakhs"]

print("Predictors:")
print(X.head())

print("\nTarget:")
print(y.head())

Predictors:
   Area_sqft  Bedrooms  Age_years  Distance_km
0       1660         2         28    12.522152
1       2094         2         22     1.174744
2       1930         4         23     2.927959
3       1895         1          5    13.606534
4       2438         3          1     1.096170

Target:
0     93.921992
1    168.574850
2    160.168584
3    148.296493
4    209.099389
Name: Price_lakhs, dtype: float64

In [7]:
correlation = data.corr(numeric_only=True)

print("Correlation Matrix:")
correlation

Correlation Matrix:

             Area_sqft  Bedrooms  Age_years  Distance_km  Price_lakhs
Area_sqft     1.000000  0.114903   0.132714    -0.055357     0.949123
Bedrooms      0.114903  1.000000  -0.191623     0.014752     0.303846
Age_years     0.132714 -0.191623   1.000000     0.075673    -0.043697
Distance_km  -0.055357  0.014752   0.075673     1.000000    -0.164470
Price_lakhs   0.949123  0.303846  -0.043697    -0.164470     1.000000

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 80
Testing samples: 20

In [9]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Multiple Linear Regression model trained successfully!")

Multiple Linear Regression model trained successfully!

In [10]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("Model Coefficients:")
coefficients

Model Coefficients:

       Feature  Coefficient
0    Area_sqft     0.079915
1     Bedrooms     7.155078
2    Age_years    -0.751651
3  Distance_km    -0.939897

In [11]:
print("Intercept:", round(model.intercept_, 4))

Intercept: 0.4304

In [12]:
y_pred = model.predict(X_test)

prediction_results = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

prediction_results.head(10)

   Actual Price  Predicted Price
0    192.866272       195.488500
1    201.583525       210.447533
2    152.478042       139.617815
3    178.772691       174.132922
4    217.064638       216.788166
5    243.201416       236.077452
6    125.613554       124.637380
7    249.174742       241.814849
8    202.412861       208.936392
9     93.921992       114.584438

In [13]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Evaluation")
print("-----------------")
print("MAE :", round(mae, 2))
print("MSE :", round(mse, 2))
print("RMSE:", round(rmse, 2))
print("R² Score:", round(r2, 4))

Model Evaluation
-----------------
MAE : 8.98
MSE : 117.91
RMSE: 10.86
R² Score: 0.9528

In [14]:
importance = coefficients.copy()

importance["Absolute_Coefficient"] = importance["Coefficient"].abs()

importance = importance.sort_values(
    by="Absolute_Coefficient",
    ascending=False
)

print("Feature Importance Based on Coefficients:")
importance

Feature Importance Based on Coefficients:

       Feature  Coefficient  Absolute_Coefficient
1     Bedrooms     7.155078              7.155078
3  Distance_km    -0.939897              0.939897
2    Age_years    -0.751651              0.751651
0    Area_sqft     0.079915              0.079915

## Interpretation

Multiple Linear Regression was used to predict house prices using multiple numerical predictors.

The predictors used were:

- Area_sqft
- Bedrooms
- Age_years
- Distance_km

The dataset was divided into training and testing sets using an 80:20 split.

The model coefficients show the direction and magnitude of the relationship between each predictor and the target variable.

A positive coefficient indicates that an increase in the feature is associated with an increase in predicted house price, while a negative coefficient indicates a decrease in predicted price, keeping other variables constant.

The model was evaluated using MAE, MSE, RMSE, and R² score.

### Conclusion

Multiple Linear Regression allows several predictors to be used together for predicting a continuous target. This task helped in understanding model training, train-test evaluation, coefficients, predictions, and feature interpretation using Scikit-learn.