In [2]:
import pandas as pd
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
print("Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Missing Values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Duplicate Rows:
0

In [5]:
print("Unique values in categorical columns:")

print("\nSex:")
print(df["Sex"].unique())

print("\nEmbarked:")
print(df["Embarked"].unique())

print("\nPclass:")
print(df["Pclass"].unique())

Unique values in categorical columns:

Sex:
['male' 'female']

Embarked:
['S' 'C' 'Q' nan]

Pclass:
[3 1 2]

In [6]:
# Check duplicate rows
duplicates_before = df.duplicated().sum()

print("Duplicate rows found:", duplicates_before)

# Remove duplicate rows
df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicate rows after cleaning:", duplicates_after)

Duplicate rows found: 0
Duplicate rows after cleaning: 0

In [7]:
# Handle missing values

# Fill missing Age values with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Embarked values with most frequent value
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop Cabin because it contains too many missing values
df = df.drop(columns=["Cabin"])

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [8]:
# Standardize categorical values

# Remove extra spaces and standardize text format
df["Sex"] = df["Sex"].str.strip().str.lower()
df["Embarked"] = df["Embarked"].str.strip().str.upper()

# Convert Sex values to consistent labels
df["Sex"] = df["Sex"].replace({
    "male": "Male",
    "female": "Female"
})

print("Standardized Sex values:")
print(df["Sex"].unique())

print("\nStandardized Embarked values:")
print(df["Embarked"].unique())

Standardized Sex values:
['Male' 'Female']

Standardized Embarked values:
['S' 'C' 'Q']

In [9]:
# Check and correct data types

df["PassengerId"] = df["PassengerId"].astype(int)
df["Survived"] = df["Survived"].astype(int)
df["Pclass"] = df["Pclass"].astype(int)
df["Age"] = df["Age"].astype(float)
df["Fare"] = df["Fare"].astype(float)

print("Data types after correction:")
print(df.dtypes)

Data types after correction:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [10]:
# Final data quality check

print("Final dataset shape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nFinal data types:")
print(df.dtypes)

print("\nFirst 5 rows of cleaned dataset:")
display(df.head())

Final dataset shape:
(891, 11)

Missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Duplicate rows:
0

Final data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

First 5 rows of cleaned dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,S

In [11]:
# Save cleaned dataset as CSV

output_file = "titanic_cleaned.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File name:", output_file)

Cleaned dataset saved successfully!
File name: titanic_cleaned.csv

In [12]:
# Data Cleaning Change Log

change_log = pd.DataFrame({
    "Issue": [
        "Missing values in Age",
        "Missing values in Embarked",
        "Excessive missing values in Cabin",
        "Duplicate rows",
        "Inconsistent categorical formatting in Sex",
        "Inconsistent categorical formatting in Embarked",
        "Data type verification"
    ],
    "Action Taken": [
        "Filled missing values using median",
        "Filled missing values using mode",
        "Removed Cabin column",
        "Checked and removed duplicate rows",
        "Standardized values to Male/Female",
        "Standardized values to uppercase S/C/Q",
        "Converted numerical columns to appropriate data types"
    ],
    "Reason": [
        "Median is less affected by extreme values",
        "Mode is suitable for categorical data",
        "Column contained a large number of missing values",
        "Duplicate records can affect analysis accuracy",
        "Ensures consistent categorical labels",
        "Ensures consistent categorical labels",
        "Ensures reliable analysis and processing"
    ]
})

display(change_log)

,Issue,Action Taken,Reason
0,Missing values in Age,Filled missing values using median,Median is less affected by extreme values
1,Missing values in Embarked,Filled missing values using mode,Mode is suitable for categorical data
2,Excessive missing values in Cabin,Removed Cabin column,Column contained a large number of missing values
3,Duplicate rows,Checked and removed duplicate rows,Duplicate records can affect analysis accuracy
4,Inconsistent categorical formatting in Sex,Standardized values to Male/Female,Ensures consistent categorical labels
5,Inconsistent categorical formatting in Embarked,Standardized values to uppercase S/C/Q,Ensures consistent categorical labels
6,Data type verification,Converted numerical columns to appropriate dat...,Ensures reliable analysis and processing

In [13]:
# Data Quality Improvement Summary

print("DATA QUALITY IMPROVEMENT SUMMARY")
print("=" * 40)

print("• Missing values were identified and handled appropriately.")
print("• Age missing values were replaced using the median.")
print("• Embarked missing values were replaced using the mode.")
print("• Cabin was removed because it contained excessive missing values.")
print("• Duplicate records were checked and removed where necessary.")
print("• Categorical values were standardized for consistency.")
print("• Numerical columns were converted to appropriate data types.")
print("• Final dataset contains 891 rows and 11 columns.")
print("• Final dataset contains 0 missing values and 0 duplicate rows.")

DATA QUALITY IMPROVEMENT SUMMARY
========================================
• Missing values were identified and handled appropriately.
• Age missing values were replaced using the median.
• Embarked missing values were replaced using the mode.
• Cabin was removed because it contained excessive missing values.
• Duplicate records were checked and removed where necessary.
• Categorical values were standardized for consistency.
• Numerical columns were converted to appropriate data types.
• Final dataset contains 891 rows and 11 columns.
• Final dataset contains 0 missing values and 0 duplicate rows.