In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
actual = np.array([100, 120, 150, 180, 200, 220, 250, 280, 300, 350])

predicted = np.array([105, 115, 145, 190, 195, 225, 240, 290, 310, 340])

print("Actual values:")
print(actual)

print("\nPredicted values:")
print(predicted)

Actual values:
[100 120 150 180 200 220 250 280 300 350]

Predicted values:
[105 115 145 190 195 225 240 290 310 340]

In [3]:
mae = mean_absolute_error(actual, predicted)
mse = mean_squared_error(actual, predicted)
rmse = np.sqrt(mse)
r2 = r2_score(actual, predicted)

print("Regression Metrics")
print("------------------")
print("MAE  :", round(mae, 4))
print("MSE  :", round(mse, 4))
print("RMSE :", round(rmse, 4))
print("R²   :", round(r2, 4))

Regression Metrics
------------------
MAE  : 7.5
MSE  : 62.5
RMSE : 7.9057
R²   : 0.9894

In [4]:
comparison = pd.DataFrame({
    "Metric": ["MAE", "MSE", "RMSE", "R²"],
    "Value": [mae, mse, rmse, r2],
    "Interpretation": [
        "Average absolute prediction error",
        "Average squared prediction error",
        "Typical prediction error with more penalty for large errors",
        "Proportion of target variance explained by the model"
    ]
})

comparison

  Metric      Value                                     Interpretation
0    MAE   7.500000                  Average absolute prediction error
1    MSE  62.500000                   Average squared prediction error
2   RMSE   7.905694  Typical prediction error with more penalty for...
3     R²   0.989380  Proportion of target variance explained by the...

In [5]:
errors = actual - predicted

error_table = pd.DataFrame({
    "Actual": actual,
    "Predicted": predicted,
    "Error": errors,
    "Absolute Error": np.abs(errors)
})

error_table

   Actual  Predicted  Error  Absolute Error
0     100        105     -5               5
1     120        115      5               5
2     150        145      5               5
3     180        190    -10              10
4     200        195      5               5
5     220        225     -5               5
6     250        240     10              10
7     280        290    -10              10
8     300        310    -10              10
9     350        340     10              10

## Interpretation of Regression Metrics

### MAE – Mean Absolute Error

MAE represents the average absolute difference between actual and predicted values.

It is easy to understand because it is expressed in the same units as the target variable.

Lower MAE indicates smaller average prediction errors.

### MSE – Mean Squared Error

MSE calculates the average of squared prediction errors.

Because errors are squared, larger errors receive greater penalty.

Lower MSE indicates better prediction performance.

### RMSE – Root Mean Squared Error

RMSE is the square root of MSE.

It is expressed in the same units as the target variable and is more sensitive to large errors than MAE.

Lower RMSE indicates better prediction performance.

### R² – R-Squared

R² measures the proportion of variation in the target variable that is explained by the regression model.

A higher R² generally indicates that the model explains more variation in the target data.

However, R² should not be used alone to judge model performance.

## Most Appropriate Metric

There is no single regression metric that is best for every situation.

MAE is useful when the average prediction error needs to be easy to interpret and all errors should have similar importance.

RMSE is useful when larger prediction errors are more important because it penalizes large errors more strongly.

MSE is useful for mathematical optimization and model training, but its squared units can make interpretation less intuitive.

R² is useful for understanding how much variation in the target is explained by the model, but it should be considered together with error-based metrics.

For practical prediction tasks, MAE or RMSE can be selected depending on whether large errors need extra attention.

## Conclusion

The four important regression evaluation metrics, MAE, MSE, RMSE, and R², were calculated and compared.

The task demonstrated how different metrics measure regression performance in different ways. MAE provides an easily interpretable average error, MSE penalizes large errors, RMSE expresses error in the original target units while emphasizing larger errors, and R² measures the proportion of variance explained by the model.

Using multiple metrics provides a more complete understanding of regression model performance.