# Task 7 – SQL Basics: Filtering, Sorting and Aggregation

## Veda Technology – Data Science Internship

**Track:** Data Science  
**Level:** Level 1 – Day 7  
**Topic:** SQL Basics – Filtering, Sorting and Aggregation

### Objective
Build foundational SQL skills by retrieving, filtering, sorting, grouping, and aggregating records from a business database.

### Tools
- Python
- SQLite
- SQL
- Pandas
- Google Colab

### Dataset
Chinook Database

In [1]:
import sqlite3
import pandas as pd
import urllib.request
import os

db_url = "https://github.com/lerocha/chinook-database/releases/download/v1.4.5/Chinook_Sqlite.sqlite"
db_file = "chinook.db"

urllib.request.urlretrieve(db_url, db_file)

conn = sqlite3.connect(db_file)

print("Chinook database loaded successfully!")
print("Database file:", db_file)

Chinook database loaded successfully!
Database file: chinook.db

In [2]:
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
""", conn)

tables

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

## SQL Query 1 – Retrieve Customers

**Question:** What are the first 10 customers in the database?

This query demonstrates the basic `SELECT` statement and `LIMIT`.

In [3]:
query1 = """
SELECT CustomerId, FirstName, LastName, Country
FROM Customer
LIMIT 10;
"""

pd.read_sql_query(query1, conn)

   CustomerId  FirstName     LastName         Country
0           1       Luís    Gonçalves          Brazil
1           2     Leonie       Köhler         Germany
2           3   François     Tremblay          Canada
3           4      Bjørn       Hansen          Norway
4           5  František  Wichterlová  Czech Republic
5           6     Helena         Holý  Czech Republic
6           7     Astrid       Gruber         Austria
7           8       Daan      Peeters         Belgium
8           9       Kara      Nielsen         Denmark
9          10    Eduardo      Martins          Brazil

## SQL Query 2 – Filter Customers by Country

**Question:** Which customers are from Brazil?

This query demonstrates filtering records using `WHERE`.

In [4]:
query2 = """
SELECT CustomerId, FirstName, LastName, Country
FROM Customer
WHERE Country = 'Brazil';
"""

pd.read_sql_query(query2, conn)

   CustomerId  FirstName   LastName Country
0           1       Luís  Gonçalves  Brazil
1          10    Eduardo    Martins  Brazil
2          11  Alexandre      Rocha  Brazil
3          12    Roberto    Almeida  Brazil
4          13   Fernanda      Ramos  Brazil

## SQL Query 3 – Filter Tracks by Composer

**Question:** Which tracks were composed by a specific composer?

This demonstrates filtering text data using `WHERE`.

In [5]:
query3 = """
SELECT TrackId, Name, Composer
FROM Track
WHERE Composer IS NOT NULL
LIMIT 15;
"""

pd.read_sql_query(query3, conn)

,TrackId,Name,Composer
0,1,For Those About To Rock (We Salute You),"Angus Young, Malcolm Young, Brian Johnson"
1,3,Fast As a Shark,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho..."
2,4,Restless and Wild,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D..."
3,5,Princess of the Dawn,Deaffy & R.A. Smith-Diesel
4,6,Put The Finger On You,"Angus Young, Malcolm Young, Brian Johnson"
5,7,Let's Get It Up,"Angus Young, Malcolm Young, Brian Johnson"
6,8,Inject The Venom,"Angus Young, Malcolm Young, Brian Johnson"
7,9,Snowballed,"Angus Young, Malcolm Young, Brian Johnson"
8,10,Evil Walks,"Angus Young, Malcolm Young, Brian Johnson"
9,11,C.O.D.,"Angus Young, Malcolm Young, Brian Johnson"
10,12,Breaking The Rules,"Angus Young, Malcolm Young, Brian Johnson"
11,13,Night Of The Long Knives,"Angus Young, Malcolm Young, Brian Johnson"
12,14,Spellbound,"Angus Young, Malcolm Young, Brian Johnson"
13,15,Go Down,AC/DC
14,16,Dog Eat Dog,AC/DC

## SQL Query 4 – Sort Tracks by Name

**Question:** What are the first 15 tracks in alphabetical order?

This demonstrates sorting using `ORDER BY`.

In [6]:
query4 = """
SELECT TrackId, Name, Composer
FROM Track
ORDER BY Name ASC
LIMIT 15;
"""

pd.read_sql_query(query4, conn)

,TrackId,Name,Composer
0,3027,"""40""",U2
1,2918,"""?""",None
2,3412,"""Eine Kleine Nachtmusik"" Serenade In G, K. 525...",Wolfgang Amadeus Mozart
3,109,#1 Zero,"Cornell, Commerford, Morello, Wilk"
4,3254,#9 Dream,None
5,602,'Round Midnight,Miles Davis
6,1833,(Anesthesia) Pulling Teeth,Cliff Burton
7,570,(Da Le) Yaleo,Santana
8,3045,(I Can't Help) Falling In Love With You,None
9,3057,(Oh) Pretty Woman,Bill Dees/Roy Orbison
10,3471,(There Is) No Greater Love (Teo Licks),Isham Jones & Marty Symes
11,1947,(We Are) The Road Crew,Clarke/Kilmister/Taylor
12,2595,(White Man) In Hammersmith Palais,Joe Strummer/Mick Jones
13,709,(Wish I Could) Hideaway,J.C. Fogerty
14,2869,...And Found,None

## SQL Query 5 – Highest-Priced Tracks

**Question:** Which tracks have the highest unit prices?

This demonstrates descending sorting.

In [7]:
query5 = """
SELECT TrackId, Name, UnitPrice
FROM Track
ORDER BY UnitPrice DESC
LIMIT 10;
"""

pd.read_sql_query(query5, conn)

   TrackId                                    Name  UnitPrice
0     2819  Battlestar Galactica: The Story So Far       1.99
1     2820                  Occupation / Precipice       1.99
2     2821                           Exodus, Pt. 1       1.99
3     2822                           Exodus, Pt. 2       1.99
4     2823                           Collaborators       1.99
5     2824                                    Torn       1.99
6     2825                  A Measure of Salvation       1.99
7     2826                                    Hero       1.99
8     2827                     Unfinished Business       1.99
9     2828                             The Passage       1.99

## SQL Query 6 – Count Customers

**Question:** How many customers are in the database?

This demonstrates the `COUNT()` aggregate function.

In [8]:
query6 = """
SELECT COUNT(*) AS Total_Customers
FROM Customer;
"""

pd.read_sql_query(query6, conn)

   Total_Customers
0               59

## SQL Query 7 – Average Track Price

**Question:** What is the average price of a track?

This demonstrates the `AVG()` aggregate function.

In [9]:
query7 = """
SELECT ROUND(AVG(UnitPrice), 2) AS Average_Track_Price
FROM Track;
"""

pd.read_sql_query(query7, conn)

   Average_Track_Price
0                 1.05

## SQL Query 8 – Total Sales

**Question:** What is the total revenue generated from invoices?

This demonstrates the `SUM()` aggregate function.

In [10]:
query8 = """
SELECT ROUND(SUM(Total), 2) AS Total_Revenue
FROM Invoice;
"""

pd.read_sql_query(query8, conn)

   Total_Revenue
0         2328.6

## SQL Query 9 – Sales by Country

**Question:** How much revenue was generated from each country?

This demonstrates `GROUP BY` with `SUM()`.

In [11]:
query9 = """
SELECT BillingCountry,
       ROUND(SUM(Total), 2) AS Total_Sales
FROM Invoice
GROUP BY BillingCountry
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query9, conn)

    BillingCountry  Total_Sales
0              USA       523.06
1           Canada       303.96
2           France       195.10
3           Brazil       190.10
4          Germany       156.48
5   United Kingdom       112.86
6   Czech Republic        90.24
7         Portugal        77.24
8            India        75.26
9            Chile        46.62
10         Ireland        45.62
11         Hungary        45.62
12         Austria        42.62
13         Finland        41.62
14     Netherlands        40.62
15          Norway        39.62
16          Sweden        38.62
17           Spain        37.62
18          Poland        37.62
19           Italy        37.62
20         Denmark        37.62
21         Belgium        37.62
22       Australia        37.62
23       Argentina        37.62

## SQL Query 10 – Number of Customers by Country

**Question:** How many customers belong to each country?

This demonstrates `GROUP BY` with `COUNT()`.

In [12]:
query10 = """
SELECT Country,
       COUNT(*) AS Customer_Count
FROM Customer
GROUP BY Country
ORDER BY Customer_Count DESC;
"""

pd.read_sql_query(query10, conn)

           Country  Customer_Count
0              USA              13
1           Canada               8
2           France               5
3           Brazil               5
4          Germany               4
5   United Kingdom               3
6         Portugal               2
7            India               2
8   Czech Republic               2
9           Sweden               1
10           Spain               1
11          Poland               1
12          Norway               1
13     Netherlands               1
14           Italy               1
15         Ireland               1
16         Hungary               1
17         Finland               1
18         Denmark               1
19           Chile               1
20         Belgium               1
21         Austria               1
22       Australia               1
23       Argentina               1

## SQL Query 11 – Average Invoice Value by Country

**Question:** What is the average invoice value for each billing country?

In [13]:
query11 = """
SELECT BillingCountry,
       ROUND(AVG(Total), 2) AS Average_Invoice_Value
FROM Invoice
GROUP BY BillingCountry
ORDER BY Average_Invoice_Value DESC;
"""

pd.read_sql_query(query11, conn)

    BillingCountry  Average_Invoice_Value
0            Chile                   6.66
1          Ireland                   6.52
2          Hungary                   6.52
3   Czech Republic                   6.45
4          Austria                   6.09
5          Finland                   5.95
6      Netherlands                   5.80
7            India                   5.79
8              USA                   5.75
9           Norway                   5.66
10         Germany                   5.59
11          France                   5.57
12          Sweden                   5.52
13        Portugal                   5.52
14          Canada                   5.43
15          Brazil                   5.43
16  United Kingdom                   5.37
17           Spain                   5.37
18          Poland                   5.37
19           Italy                   5.37
20         Denmark                   5.37
21         Belgium                   5.37
22       Australia                   5.37
23       Argentina                   5.37

## SQL Query 12 – Countries with High Total Sales

**Question:** Which countries generated more than $50 in total sales?

This demonstrates the use of `HAVING` after aggregation.

In [14]:
query12 = """
SELECT BillingCountry,
       ROUND(SUM(Total), 2) AS Total_Sales
FROM Invoice
GROUP BY BillingCountry
HAVING SUM(Total) > 50
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query12, conn)

   BillingCountry  Total_Sales
0             USA       523.06
1          Canada       303.96
2          France       195.10
3          Brazil       190.10
4         Germany       156.48
5  United Kingdom       112.86
6  Czech Republic        90.24
7        Portugal        77.24
8           India        75.26

## SQL Query 13 – Customers with Multiple Invoices

**Question:** Which customers have more than 5 invoices?

This demonstrates `GROUP BY` and `HAVING`.

In [15]:
query13 = """
SELECT CustomerId,
       COUNT(*) AS Invoice_Count
FROM Invoice
GROUP BY CustomerId
HAVING COUNT(*) > 5
ORDER BY Invoice_Count DESC;
"""

pd.read_sql_query(query13, conn)

    CustomerId  Invoice_Count
0            1              7
1            2              7
2            3              7
3            4              7
4            5              7
5            6              7
6            7              7
7            8              7
8            9              7
9           10              7
10          11              7
11          12              7
12          13              7
13          14              7
14          15              7
15          16              7
16          17              7
17          18              7
18          19              7
19          20              7
20          21              7
21          22              7
22          23              7
23          24              7
24          25              7
25          26              7
26          27              7
27          28              7
28          29              7
29          30              7
30          31              7
31          32              7
32          33              7
33          34              7
34          35              7
35          36              7
36          37              7
37          38              7
38          39              7
39          40              7
40          41              7
41          42              7
42          43              7
43          44              7
44          45              7
45          46              7
46          47              7
47          48              7
48          49              7
49          50              7
50          51              7
51          52              7
52          53              7
53          54              7
54          55              7
55          56              7
56          57              7
57          58              7
58          59              6

## SQL Query 14 – Maximum Invoice Amount

**Question:** What is the largest individual invoice amount?

In [16]:
query14 = """
SELECT InvoiceId,
       CustomerId,
       Total
FROM Invoice
ORDER BY Total DESC
LIMIT 10;
"""

pd.read_sql_query(query14, conn)

   InvoiceId  CustomerId  Total
0        404           6  25.86
1        299          26  23.86
2         96          45  21.86
3        194          46  21.86
4         89           7  18.86
5        201          25  18.86
6         88          57  17.91
7        306           5  16.86
8        313          43  16.86
9        103          24  15.86

## SQL Query 15 – Minimum and Maximum Track Price

**Question:** What are the minimum and maximum track prices?

In [17]:
query15 = """
SELECT
    MIN(UnitPrice) AS Minimum_Price,
    MAX(UnitPrice) AS Maximum_Price
FROM Track;
"""

pd.read_sql_query(query15, conn)

   Minimum_Price  Maximum_Price
0           0.99           1.99

## SQL Query 16 – Number of Tracks by Genre

**Question:** How many tracks are available in each genre?

In [18]:
query16 = """
SELECT g.Name AS Genre,
       COUNT(t.TrackId) AS Track_Count
FROM Genre g
JOIN Track t
ON g.GenreId = t.GenreId
GROUP BY g.GenreId, g.Name
ORDER BY Track_Count DESC;
"""

pd.read_sql_query(query16, conn)

                 Genre  Track_Count
0                 Rock         1297
1                Latin          579
2                Metal          374
3   Alternative & Punk          332
4                 Jazz          130
5             TV Shows           93
6                Blues           81
7            Classical           74
8                Drama           64
9             R&B/Soul           61
10              Reggae           58
11                 Pop           48
12          Soundtrack           43
13         Alternative           40
14         Hip Hop/Rap           35
15   Electronica/Dance           30
16         Heavy Metal           28
17               World           28
18    Sci Fi & Fantasy           26
19      Easy Listening           24
20              Comedy           17
21          Bossa Nova           15
22     Science Fiction           13
23       Rock And Roll           12
24               Opera            1

## SQL Query 17 – Revenue by Customer

**Question:** Which customers generated the highest total revenue?

In [19]:
query17 = """
SELECT
    c.CustomerId,
    c.FirstName || ' ' || c.LastName AS Customer_Name,
    ROUND(SUM(i.Total), 2) AS Total_Spent
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, c.FirstName, c.LastName
ORDER BY Total_Spent DESC
LIMIT 10;
"""

pd.read_sql_query(query17, conn)

   CustomerId       Customer_Name  Total_Spent
0           6         Helena Holý        49.62
1          26  Richard Cunningham        47.62
2          57          Luis Rojas        46.62
3          45     Ladislav Kovács        45.62
4          46       Hugh O'Reilly        45.62
5          24       Frank Ralston        43.62
6          28       Julia Barnett        43.62
7          37     Fynn Zimmermann        43.62
8           7       Astrid Gruber        42.62
9          25      Victor Stevens        42.62

## SQL Query 18 – Sales by Employee

**Question:** How much sales revenue is associated with each sales-support employee?

In [20]:
query18 = """
SELECT
    e.EmployeeId,
    e.FirstName || ' ' || e.LastName AS Employee_Name,
    ROUND(SUM(i.Total), 2) AS Sales_Handled
FROM Employee e
JOIN Customer c
ON e.EmployeeId = c.SupportRepId
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY e.EmployeeId, e.FirstName, e.LastName
ORDER BY Sales_Handled DESC;
"""

pd.read_sql_query(query18, conn)

   EmployeeId  Employee_Name  Sales_Handled
0           3   Jane Peacock         833.04
1           4  Margaret Park         775.40
2           5  Steve Johnson         720.16

## SQL Query 19 – Tracks Longer Than 5 Minutes

**Question:** Which tracks have a duration longer than five minutes?

This demonstrates filtering using a numerical condition.

In [21]:
query19 = """
SELECT TrackId,
       Name,
       ROUND(Milliseconds / 60000.0, 2) AS Duration_Minutes
FROM Track
WHERE Milliseconds > 300000
ORDER BY Duration_Minutes DESC
LIMIT 15;
"""

pd.read_sql_query(query19, conn)

    TrackId                               Name  Duration_Minutes
0      2820             Occupation / Precipice             88.12
1      3224            Through a Looking Glass             84.81
2      3244        Greetings from Earth, Pt. 1             49.34
3      3242            The Man With Nine Lives             49.28
4      3227        Battlestar Galactica, Pt. 2             49.27
5      3226        Battlestar Galactica, Pt. 1             49.21
6      3243          Murder On the Rising Star             48.93
7      3228        Battlestar Galactica, Pt. 3             48.80
8      3248                  Take the Celestra             48.79
9      3239                      Fire In Space             48.78
10     3232                    The Long Patrol             48.75
11     3235           The Magnificent Warriors             48.75
12     3234  The Gun On Ice Planet Zero, Pt. 2             48.74
13     3237           The Living Legend, Pt. 1             48.74
14     3247                Experiment In Terra             48.73

## SQL Query 20 – Sales by Year

**Question:** How much revenue was generated in each invoice year?

This demonstrates grouping using a date component.

In [22]:
query20 = """
SELECT
    strftime('%Y', InvoiceDate) AS Sales_Year,
    ROUND(SUM(Total), 2) AS Annual_Sales
FROM Invoice
GROUP BY Sales_Year
ORDER BY Sales_Year;
"""

pd.read_sql_query(query20, conn)

  Sales_Year  Annual_Sales
0       2009        449.46
1       2010        481.45
2       2011        469.58
3       2012        477.53
4       2013        450.58

## SQL Query 21 – Customers from the USA

**Question:** How many customers are from the USA?

In [23]:
query21 = """
SELECT COUNT(*) AS USA_Customers
FROM Customer
WHERE Country = 'USA';
"""

pd.read_sql_query(query21, conn)

   USA_Customers
0             13

## SQL Query 22 – Top 10 Most Expensive Tracks

**Question:** Which tracks have the highest prices?

In [24]:
query22 = """
SELECT Name, UnitPrice
FROM Track
ORDER BY UnitPrice DESC
LIMIT 10;
"""

pd.read_sql_query(query22, conn)

                                     Name  UnitPrice
0  Battlestar Galactica: The Story So Far       1.99
1                  Occupation / Precipice       1.99
2                           Exodus, Pt. 1       1.99
3                           Exodus, Pt. 2       1.99
4                           Collaborators       1.99
5                                    Torn       1.99
6                  A Measure of Salvation       1.99
7                                    Hero       1.99
8                     Unfinished Business       1.99
9                             The Passage       1.99

## SQL Query 23 – Number of Invoices per Country

**Question:** How many invoices were generated in each country?

In [25]:
query23 = """
SELECT BillingCountry,
       COUNT(*) AS Invoice_Count
FROM Invoice
GROUP BY BillingCountry
ORDER BY Invoice_Count DESC;
"""

pd.read_sql_query(query23, conn)

    BillingCountry  Invoice_Count
0              USA             91
1           Canada             56
2           France             35
3           Brazil             35
4          Germany             28
5   United Kingdom             21
6         Portugal             14
7   Czech Republic             14
8            India             13
9           Sweden              7
10           Spain              7
11          Poland              7
12          Norway              7
13     Netherlands              7
14           Italy              7
15         Ireland              7
16         Hungary              7
17         Finland              7
18         Denmark              7
19           Chile              7
20         Belgium              7
21         Austria              7
22       Australia              7
23       Argentina              7

## SQL Query 24 – Customers with Spending Above $40

**Question:** Which customers spent more than $40?

In [26]:
query24 = """
SELECT
    c.CustomerId,
    c.FirstName || ' ' || c.LastName AS Customer_Name,
    ROUND(SUM(i.Total), 2) AS Total_Spent
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, c.FirstName, c.LastName
HAVING SUM(i.Total) > 40
ORDER BY Total_Spent DESC;
"""

pd.read_sql_query(query24, conn)

    CustomerId          Customer_Name  Total_Spent
0            6            Helena Holý        49.62
1           26     Richard Cunningham        47.62
2           57             Luis Rojas        46.62
3           45        Ladislav Kovács        45.62
4           46          Hugh O'Reilly        45.62
5           24          Frank Ralston        43.62
6           28          Julia Barnett        43.62
7           37        Fynn Zimmermann        43.62
8            7          Astrid Gruber        42.62
9           25         Victor Stevens        42.62
10          44       Terhi Hämäläinen        41.62
11           5  František Wichterlová        40.62
12          43       Isabelle Mercier        40.62
13          48  Johannes Van der Berg        40.62

## SQL Query 25 – Number of Tracks by Media Type

**Question:** How many tracks exist for each media type?

In [27]:
query25 = """
SELECT
    m.Name AS Media_Type,
    COUNT(t.TrackId) AS Track_Count
FROM MediaType m
JOIN Track t
ON m.MediaTypeId = t.MediaTypeId
GROUP BY m.MediaTypeId, m.Name
ORDER BY Track_Count DESC;
"""

pd.read_sql_query(query25, conn)

                    Media_Type  Track_Count
0              MPEG audio file         3034
1     Protected AAC audio file          237
2  Protected MPEG-4 video file          214
3               AAC audio file           11
4     Purchased AAC audio file            7

# Business Insights

Based on the SQL analysis, the following business insights were identified:

### 1. Geographic Sales
Sales can be grouped by billing country to identify the strongest geographic markets. This information can help businesses focus marketing and customer-retention strategies on high-performing markets.

### 2. Customer Spending
The customer-level revenue analysis identifies high-value customers. These customers could be targeted with loyalty programs, personalized offers, or retention strategies.

### 3. Product Pricing
The analysis of track prices identifies the pricing range and the highest-priced products. This can help understand the pricing structure of the product catalog.

### 4. Product Categories
Grouping tracks by genre shows which music categories have the largest number of products. This can help businesses understand catalog composition and customer interests.

### 5. Sales Performance
Sales associated with support representatives provide a way to compare sales performance and understand how revenue is distributed across employees.

# Conclusion

This task provided practical experience with SQL fundamentals using the Chinook business database.

A total of 25 SQL queries were created using SELECT, WHERE, ORDER BY, GROUP BY, HAVING, aggregate functions, and JOIN operations.

The analysis demonstrated how SQL can be used to retrieve business data, filter records, sort results, calculate metrics, group information, and generate useful business insights.

The project strengthened foundational SQL skills required for entry-level Data Analyst and Data Science roles.

In [28]:
conn.close()
print("Database connection closed successfully.")

Database connection closed successfully.