In [29]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [30]:
data = {
    "Name": ["Srujan", "Vaishu", "JanAvi", "Leesha", "Nambratha"],
    "Age": [22, 21, 22, 20, 23],
    "Marks": [85, 78, 92, 88, 75],
    "Department": ["ISE", "CSE-AIML", "ISE", "CSE", "CS"]
}

df = pd.DataFrame(data, index=["S1", "S2", "S3", "S4", "S5"])

df

         Name  Age  Marks Department
S1     Srujan   22     85        ISE
S2     Vaishu   21     78   CSE-AIML
S3     JanAvi   22     92        ISE
S4     Leesha   20     88        CSE
S5  Nambratha   23     75         CS

In [31]:
print("LOC Example 1:")
df.loc["S1"]

LOC Example 1:

Name          Srujan
Age               22
Marks             85
Department       ISE
Name: S1, dtype: object

In [32]:
print("LOC Example 2:")
df.loc[["S1", "S3", "S5"]]

LOC Example 2:

         Name  Age  Marks Department
S1     Srujan   22     85        ISE
S3     JanAvi   22     92        ISE
S5  Nambratha   23     75         CS

In [33]:
print("LOC Example 3:")
df.loc["S2", "Marks"]

LOC Example 3:

np.int64(78)

In [34]:
print("LOC Example 4:")
df.loc[["S1", "S3"], ["Name", "Marks"]]

LOC Example 4:

      Name  Marks
S1  Srujan     85
S3  JanAvi     92

In [35]:
print("LOC Example 5:")
df.loc[df["Marks"] > 80, ["Name", "Marks"]]

LOC Example 5:

      Name  Marks
S1  Srujan     85
S3  JanAvi     92
S4  Leesha     88

In [36]:
print("ILOC Example 1:")
df.iloc[0]

ILOC Example 1:

Name          Srujan
Age               22
Marks             85
Department       ISE
Name: S1, dtype: object

In [37]:
print("ILOC Example 2:")
df.iloc[[0, 2, 4]]

ILOC Example 2:

         Name  Age  Marks Department
S1     Srujan   22     85        ISE
S3     JanAvi   22     92        ISE
S5  Nambratha   23     75         CS

In [38]:
print("ILOC Example 3:")
df.iloc[1, 2]

ILOC Example 3:

np.int64(78)

In [39]:
print("ILOC Example 4:")
df.iloc[[0, 2], [0, 2]]

ILOC Example 4:

      Name  Marks
S1  Srujan     85
S3  JanAvi     92

In [40]:
print("ILOC Example 5:")
df.iloc[1:4, 0:3]

ILOC Example 5:

      Name  Age  Marks
S2  Vaishu   21     78
S3  JanAvi   22     92
S4  Leesha   20     88

In [41]:
comparison = pd.DataFrame({
    "Feature": [
        "Selection method",
        "Rows",
        "Columns",
        "Uses column names?",
        "Uses integer positions?"
    ],
    "loc[]": [
        "Label-based",
        "Row labels",
        "Column labels",
        "Yes",
        "No"
    ],
    "iloc[]": [
        "Position-based",
        "Integer positions",
        "Integer positions",
        "No",
        "Yes"
    ]
})

comparison

                   Feature          loc[]             iloc[]
0         Selection method    Label-based     Position-based
1                     Rows     Row labels  Integer positions
2                  Columns  Column labels  Integer positions
3       Uses column names?            Yes                 No
4  Uses integer positions?             No                Yes

## Interview Questions

### 1. What is the difference between loc[] and iloc[]?

`loc[]` performs label-based selection, while `iloc[]` performs position-based selection using integer indexes.

Example:

`df.loc["S1"]` selects the row with label S1.

`df.iloc[0]` selects the first row based on its position.

### 2. When should you use loc[]?

Use `loc[]` when you want to select data using row labels, column names, or conditions.

### 3. Can iloc[] use column names?

No. `iloc[]` uses integer positions only.

For example:

`df.iloc[0, 2]`

selects the first row and third column.

To select using column names, use `loc[]`.

## Observations

`loc[]` and `iloc[]` are important Pandas DataFrame selection methods.

- `loc[]` uses labels.
- `iloc[]` uses integer positions.
- `loc[]` can use column names.
- `iloc[]` cannot directly use column names.
- Both methods can be used to select rows, columns, or specific values.

The examples demonstrated different ways to select data using both methods.